plugins:
  - prettier-plugin-java
    
arrowParens: "avoid"
bracketSpacing: true
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 120
proseWrap: always
quoteProps: as-needed
requirePragma: false
semi: false
tabWidth: 2
trailingComma: "all"
useTabs: false
